- name: Install the AD-Domain-Services
  tags: InstallAD
  win_feature:
    name: AD-Domain-Services
    state: present

- name: Setup Domain
  tags: Setup
  win_domain:
    dns_domain_name: "{{ad_domain_name}}"
    safe_mode_password: "{{ad_safe_mode_password}}"

- name: reboot the machine
  tags: Reboot
  win_reboot: 

- name: Print out the domain list availble
  tags: Print
  win_shell: "nltest /dclist:{{ad_domain_name}}"
