- hosts: jumpbox
  gather_facts: true
  tasks:

   - name: Fetch Instance Info
     os_server_facts:
      cloud: ospcloud
      region_name: RegionOne
     register: result
   - name: Add host to
     add_host:
      name: "{{ item.public_v4 }}"
      group: "{{ item.metadata.group }}"
     with_items: "{{result.ansible_facts.openstack_servers}}"
   - name: Add host
     add_host:
      name: "{{ item.public_v4 }}"
      group: "{{ item.metadata.deployment_name }}"
     with_items: "{{result.ansible_facts.openstack_servers}}"

- hosts: webservers
  tags: haproxy
  gather_facts: false
  become: yes
  roles:
   - { role: "./roles/haproxy" }

- hosts: all
  gather_facts: false # remove later! speeds up testing
  become: true
  roles:
   - { role: "./roles/base_configure" } 

- hosts: databaseservers
  tags: postgres
  gather_facts: true
  become: true
  roles:
   - { role: "./roles/postgres/geerlingguy.postgresql" }

- hosts: apbaseservers
  tags: tomcat
  gather_facts: false
  become: true
  roles:
   - { role: "./roles/tomcat" }

- hosts: apbaseservers
  gather_facts: false
  become: true
  roles:
   - { role: "./roles/app" }

- hosts: apbaseservers
  gather_facts: false
  become: true
  roles:
  - { role: "./roles/apache" }
