---
#- name: deploy postgres
#  hosts: apps
#  gather_facts: false
#  become: true
#  hosts: appdbs
#  tasks:
  #- name: install progress
  #  command: "yum install -y postgresql-server"

  - name: install postgres
    yum:
      name: postgresql-server
      state: latest
  - name: enable apache at boot
    service:
      name: postgresql
      enabled: yes
  - name: tell user to finish setting up postgres
    debug:
      msg: "Either uncomment the postgres setup or manually login and initialize"

 # only run the next 2 tasks once!

#  - stat: path=/ver/lib/pgsql/data/pg_hba.conf
#    register: exi

#  - name: initilize postgres
#    command: postgresql-setup initdb
#    when: not exi.stat.exists

#  - name: initilize postgres some more
#    command: chkconfig postgresql on
#    when: not exi.stat.exists
#    -------------------------------
  - name: start postgres
    service:
      name: postgresql.service
      state: started


