---
- name: install active directory
  win_feature:
    name: AD-Domain-Services
    state: present

- name: setup domain controller
  win_domain:
    dns_domain_name: "{{ ad_domain_name }}"
    safe_mode_password: "{{ ad_safe_mode_password }}"

- name: reboot win server
  win_reboot:

- name: get domain list
  win_shell: nltest /dclist:{{ ad_domain_name }}
  register: result

- name: print domain list
  debug: var=result
