---

- name: Create a Role to Configure OpenSSH service on Windows Server 2012.
  hosts: windows
  vars_files: 
    - ssh_var.yml
  roles:
    - win_package_install
    - win_service_manage
    - win_firewall
