---
# Bad ansible! This playbook is an example of poor/bad practices!
# Bad practices may include:
#
#   Poor formatting and structure
#   Poor use of YAML - but good enough to parse
#   Inconsistent style
#   Incorrect use of modules
#   Poor module choice
#   Unclear names
#   Hard coding / poor use of variables
#   Roles - what are roles?
#   Bare variables
#   No use of handlers

- name: configuration
  tags: configuration
  hosts: tag_AnsibleGroup_apps,tag_AnsibleGroup_appdbs,tag_AnsibleGroup_frontends,
  gather_facts: false # remove later! speeds up testing
  become: true
  roles:
   - { role: "./roles/base_configure" } 

- name: deploy postgres
  tags: postgres
  hosts: tag_AnsibleGroup_appdbs
  gather_facts: true
#  become: True
  roles:
   - postgreSQL


- name: deploy tomcat
  tags: tomcat
  hosts: tag_AnsibleGroup_apps
  gather_facts: false
  become: true
  roles:
   - { role: "./roles/tomcat" }

- name: index.html on app
  tags: app
  hosts: tag_AnsibleGroup_apps
  gather_facts: false
  become: true
  become_user: postgres
  roles:
   - { role: "./roles/app" }

- name: deploy apache
  tags: apache
  hosts: tag_AnsibleGroup_apps
  gather_facts: false
  become: true
  roles:
  - { role: "./roles/apache" }


- name: deploy haproxy
  tags: haproxy
  hosts: tag_AnsibleGroup_frontends
  gather_facts: false # remove later! speeds up testing
  become: true
  roles:
   - { role: "./roles/haproxy" }


